### ISSUE TITLE
Question: Control Open Gamma Detector via console in Gamma MCA

### ISSUE THREAD

**Issue by dc1rdb** [Open-Gamma-Project/Gamma-MCA#11]
Using serial console in Gamma MCA, connecting to the serial interface of the Open Gamma Detector is not working for me.
Pico shows up correctly in the Port menu and spectrum recording also works just fine via the serial interface of Gamma MCA.
Of course, connecting to the serial interface of Open Gamma Detector via Arduino IDE works.
Am I missing something here?
Many thanks in advance!

**Comment by dc1rdb** [comment]
It appears that the console commands are actually being sent to the OGD (verified with reboot command, which works). But no answers from OGD are being displayed in the console window (eg after sending read info).

**Comment by Phoenix1747** [comment]
Hi,

the serial console can, at the moment, only write commands to the serial connection. There is no serial read capability with this current version. This feature was only added because of an request for rudimentary writing, but there will be support for this feature somewhere in the future. Sorry if this caused some confusion.

**Comment by Phoenix1747** [comment]
Should be more clear now. [deaf308](https://github.com/Open-Gamma-Project/Gamma-MCA/commit/deaf3082352e112514169078b90e268c1cdefc35)

**Comment by Phoenix1747** [comment]
Update: I added a full-fledged serial console with version 2022-12-28. Have fun! 🙂 
902ed50bd1d1a3598635f02920443d01fd4597f5
