### ISSUE TITLE
Franta

### ISSUE THREAD

**Issue by FrantisekMaly** [Open-Gamma-Project/Gamma-MCA#13]
Hello, 
when selecting set mode geiger, only 0  are sent to the serial port. 
When choosing energy, everything is fine. 
Thank you

**Comment by Phoenix1747** [comment]
Yes, that is correct. Geiger mode does **not** and has **never** measured pulse energy. That's why it is called Geiger mode, it just counts pulses. In exchange for that the dead time's a lot shorter.

**Comment by FrantisekMaly** [comment]
Hello

Thank you for the information. The fact that the geiger mode does not display the energy of pulses is clear. I was expecting information about the number of pulses on the serial output. I did not realize that the number of "zeros" sent is actually the number of pulses in the geiger mode, and that I have to relate them to time and count them in my application. Thank you again for the information and for a nice project.

From the Czech Republic greetings

Frantisek Maly

**Comment by Phoenix1747** [comment]
Oh, yes, it sends the zeros so that Geiger and energy mode are both compatible with the cps measurement done in Gamma MCA. The way it is done is by simply counting the number of pulses per channel and since there is none in Geiger mode, it just prints out zeros accordingly. Otherwise, there is no sense in plotting a pulse height diagram for a geiger counter obviously, so the whole plot window is irrelevant.

If you choose the spectrum histogram output in the Open Gamma Detector, you will get an empty histogram with all the pulses accumulated in channel number 0. Maybe this will be more helpful for your use case.
